name: Insert Data Workflow

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  insert_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version

    - name: Install dependencies
      run: |
        pip install pymongo
        pip install pandas

    - name: Run insert_data.py
      run: python API/insert_data.py # Adjust path as necessary
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}