name: Automate Update Data Script

on:
  workflow_dispatch:  # Permet le déclenchement manuel
  schedule:
    - cron: '0 9 * * *'  # Exécute tous les jours à 9h00 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Update SSL Certificates
      run: sudo apt-get update && sudo apt-get install -y ca-certificates

    - name: Update certifi
      run: pip install --upgrade certifi

    - name: Install dependencies
      run: |
        pip install pymongo
        pip install yfinance
        # Ajoutez ici d'autres dépendances si nécessaire

    - name: Execute update_data.py
      run: python API/update_data.py
