name: Execute Update Data Script

on:
  workflow_dispatch:
  schedule:
    # Exécute tous les jours à 9:00 AM UTC; ajustez selon vos besoins
    - cron:  '0 9 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install yfinance
        pip install pymongo
        # Ajoutez d'autres dépendances nécessaires ici

    - name: Run update_data.py
      run: python API/update_data.py
