name: Automatisation de récupération de données

on:
  workflow_dispatch:  # Permet le déclenchement manuel
  schedule:
    - cron: '0 9 * * *'  # Exécute tous les jours à 9h00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        pip install pymongo
        pip install yfinance

    - name: Exécuter update_data.py
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}
        MONGO_APP_NAME: ${{ secrets.MONGO_APP_NAME }}
      run: python API/update_data.py
