name: Automatisation de récupération de données des cryptos

on:
  schedule:
    - cron: '0 6 * * *'  # Exécute tous les jours ouvrables à 6h00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        pip install pymongo
        pip install yfinance

    - name: Obtenir l'adresse IP de l'hôte d'exécution
      run: curl ifconfig.me
    - name: Exécuter update_data_crypto.py
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        MONGO_COLLECTION_NAME_CRYPTO: ${{ secrets.MONGO_COLLECTION_NAME_CRYPTO }}
        MONGO_APP_NAME: ${{ secrets.MONGO_APP_NAME }}
      run: python API_crypto/update_data_crypto.py